/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.Principal;

import ec.edu.ups.conexion.coneccion;
import ec.edu.ups.modelo.SalarioEdad;
import java.awt.Color;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;

import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author USER
 */
public class Principal extends javax.swing.JFrame {
coneccion baseDatos;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
         baseDatos =new coneccion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("REPORTES NORMALES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("REPORTES DINAMICOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("GRAFICA PASTEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("GRAFICA BARRAS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("GRAFICA LINEAS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setText("Mostrar Registros y Estadisticas");

        jLabel2.setText("INGRESAR CEDULA :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(65, 65, 65)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtcedula)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      // Fuente de Datos
       DefaultPieDataset data = new DefaultPieDataset();
        baseDatos.conectar();
        try{
             
          Statement obj= baseDatos.getConexionBD().createStatement();
       String sql="SELECT * FROM\"PERSONA\";";
               ResultSet res=obj.executeQuery(sql);
               int edad15=0;
               int edad16hasta20=0;
               int edad21hasta30=0;
               int edad31hasta40=0;
               int edadmayor40=0;
               while(res.next()){
                   int edad=res.getInt(4);
                   if(edad<15)edad15 ++;
                   if(edad>15 && edad<=20)edad16hasta20 ++;
                   if(edad>15 && edad<=20)edad21hasta30 ++;
                   if(edad>15 && edad<=20)edad31hasta40 ++;
                   if(edad>40)edadmayor40 ++;
               }
               baseDatos.desconectar();
        data.setValue("EDAD DESDE LOS 10",edad15);
        data.setValue("EDAD ENTRE 10 Y 20", edad16hasta20);
        data.setValue("EDAD ENTRE 21 A 30", edad21hasta30);
        data.setValue("EDAD ENTRE 31 A 40", edad31hasta40);
        data.setValue("EDAD MAYOR A 41" , edadmayor40);
        // Creando el Grafico
        JFreeChart chart = ChartFactory.createPieChart(
         "ESTADISTICA DE EDADES", 
         data, 
         true, 
         true, 
         false);
 
        // Mostrar Grafico
        ChartFrame frame = new ChartFrame("EDADES", chart);
        frame.pack();
        frame.setVisible(true);
         }catch(SQLException ex){
             ex.printStackTrace();
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try{
        baseDatos.conectar();
        File reporteArchivo= new File("src/ec/edu/ups/Reporst/persona.jasper");
            JasperReport reporteJasper = (JasperReport) JRLoader.loadObject(reporteArchivo);
            
            JasperPrint jasperPrint = JasperFillManager.fillReport(reporteJasper, null, baseDatos.getConexionBD()); 
            
            JasperExportManager.exportReportToPdfFile(jasperPrint, "ReporteNormal.pdf");
            
            JasperViewer.viewReport(jasperPrint);
            
            baseDatos.desconectar();
    }catch(JRException ex){
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        baseDatos.conectar();
        try{
        Statement sta = baseDatos.getConexionBD().createStatement();
        String sql = "SELECT * FROM \"PERSONA\";";
        ResultSet respuesta = sta.executeQuery(sql);
        int edadmen15h=0;
        int edadmen15m=0;
        int edad16a20h=0;
        int edad16a20m=0;
        int edad21a30h=0;
        int edad21a30m=0;
        int edad31a40h=0;
        int edad31a40m=0;
        int edadmay40h=0;
        int edadmay40m=0;
        
        double edadmen15hTotal=0;
        double edadmen15mTotal=0;
        double edad16a20hTotal=0;
        double edad16a20mTotal=0;
        double edad21a30hTotal=0;
        double edad21a30mTotal=0;
        double edad31a40hTotal=0;
        double edad31a40mTotal=0;
        double edadmay40htotal=0;
        double edadmay40mTodal=0;
        
        while(respuesta.next()){
            int edad=respuesta.getInt(4);
            String genero=respuesta.getString(8);
            
            if(edad>15 && edad <=20 && genero.equals("MASCULINO")){ edad16a20h++; edad16a20hTotal+=respuesta.getDouble(7);}
            if(edad>15 && edad <=20 && genero.equals("FEMENINO")){ edad16a20m++;  edad16a20mTotal+=respuesta.getDouble(7);}
            if(edad>=21 && edad <=30 && genero.equals("MASCULINO")) {edad21a30h++; edad21a30hTotal+=respuesta.getDouble(7);}
            if(edad>=21 && edad <=30 && genero.equals("FEMENINO")) {edad21a30m++;  edad21a30mTotal+=respuesta.getDouble(7);}
            if(edad>=31 && edad <=40 && genero.equals("MASCULINO")){ edad31a40h++; edad31a40hTotal+=respuesta.getDouble(7);}
            if(edad>=31 && edad <=40 && genero.equals("FEMENINO")) {edad31a40m++;  edad31a40mTotal+=respuesta.getDouble(7);}
            if(edad>=41 && edad <=100 && genero.equals("MASCULINO")) {edadmay40h++;  edadmay40htotal+=respuesta.getDouble(7);}
            
            if(edad>40 && edad <=100 && genero.equals("FEMENINO")) {edadmay40m++;   edadmay40mTodal+=respuesta.getDouble(7);}
           
        }
        baseDatos.desconectar();
       
        if(edadmen15h==0) edadmen15h=1;
        if(edadmen15m==0) edadmen15m=1;
        if(edad16a20m==0) edad16a20m=1;
        if(edad16a20h==0) edad16a20h=1;
        if(edad21a30m==0) edad21a30m=1;
        if(edad21a30h==0) edad21a30h=1;
        if(edad31a40m==0) edad31a40m=1;
        if(edad31a40h==0) edad31a40h=1;
        if(edadmay40m==0) edadmay40m=1;
        if(edadmay40h==0) edadmay40h=1;
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(edadmen15mTotal/edadmen15m, "Mujeres", "menores a 15");
        dataset.setValue(edadmen15hTotal/edadmen15h, "Hombres", "menores a 15");
        dataset.setValue(edad16a20mTotal/edad16a20m, "Mujeres", "entre 16 y 20");
        dataset.setValue(edad16a20hTotal/edad16a20h, "Hombres", "entre 16 y 20");
        dataset.setValue(edad21a30mTotal/edad21a30m, "Mujeres", "entre 21 y 30");
        dataset.setValue(edad21a30hTotal/edad21a30h, "Hombres", "entre 21 y 30");
        dataset.setValue(edad31a40mTotal/edad31a40m, "Mujeres", "entre 31 y 40");
        dataset.setValue(edad31a40hTotal/edad31a40h, "Hombres", "entre 31 y 40");
        dataset.setValue(edadmay40mTodal/edadmay40m, "Mujeres", "mayores a 40");
        dataset.setValue(edadmay40htotal/edadmay40h, "Hombres", "mayores a 40");
        
        JFreeChart chart = ChartFactory.createBarChart3D
        ("Participacion por Genero","Genero", "Salario Promedio", 
        dataset, PlotOrientation.VERTICAL, true,true, false);
        chart.setBackgroundPaint(Color.cyan);
        chart.getTitle().setPaint(Color.blue); 
        CategoryPlot p = chart.getCategoryPlot(); 
        p.setRangeGridlinePaint(Color.green); 
        ChartFrame frame = new ChartFrame("Genero y salario", chart);
        frame.pack();
        frame.setVisible(true);
        
       }catch(SQLException ex){
       ex.printStackTrace();
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      try {
            DefaultCategoryDataset line_chart_dataset = new DefaultCategoryDataset();
            baseDatos.conectar();
            List<SalarioEdad> lista=new ArrayList<SalarioEdad>();
            String sql="SELECT * FROM \"PERSONA\";";
            Statement sta=baseDatos.getConexionBD().createStatement();
            ResultSet resultado=sta.executeQuery(sql);
            while(resultado.next()){
                int edadPersona=resultado.getInt(4);
                SalarioEdad salarioEdad=new SalarioEdad();
                salarioEdad.setEdad(edadPersona);
                salarioEdad.setSumatoria(resultado.getDouble(7));
                lista.add(salarioEdad);
            }
            baseDatos.desconectar();
        
            for(SalarioEdad salarioEdad : lista){
           
        line_chart_dataset.addValue(salarioEdad.obtenerPromedio(), "Salario Promedio", Integer.toString(salarioEdad.getEdad()));
               
           
        }
            
            JFreeChart chart=ChartFactory.createLineChart("Salario Promedio",
                "Edad","Sueldo Promedio",line_chart_dataset,PlotOrientation.VERTICAL,
                true,true,false);
            ChartFrame frame = new ChartFrame("Pomedio Salario", chart);
            frame.pack();
            frame.setVisible(true);
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
           // Logger.getLogger(GeneradorPDF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
            baseDatos.conectar();
            File reporteArchivo = new File("src/ec/edu/ups/Reporst/Direc.jasper");
            JasperReport reporteJasper = (JasperReport) JRLoader.loadObject(reporteArchivo);
            Map parametro=new HashMap();
            String cedula=txtcedula.getText();
            
            parametro.put("PER_CEDULA", cedula);
              
            JasperPrint jasperPrint = JasperFillManager.fillReport(reporteJasper, parametro, baseDatos.getConexionBD()); 
          
            JasperExportManager.exportReportToPdfFile(jasperPrint, "Reporte con cedula.pdf");
            
            JasperViewer.viewReport(jasperPrint);
            
            baseDatos.desconectar();
        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtcedula;
    // End of variables declaration//GEN-END:variables
}
